build          = "gradlew"
arguments      = [ "clean", "build", "install" ]
jdk11          = false
androidVersion = 28
customTools = [ "https://docs.muse.dev/scripts/pmd.sh rulesets/java/quickstart.xml" ]
