name: Android CI

on: [push,pull_request]

jobs:
  build:
    name: Android Compilation Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Make Gradle executable
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Local publishing test to ensure working
      run: ./gradlew clean build signAarPublication publishAarPublicationToMavenLocal
      env:
        GPG_SIGN_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_SIGN_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
  artifactory:
    name: Release to Artifactory
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Generate Artifactory artifact and publish release and upload
        run: ./gradlew clean build signAarPublication artifactoryPublish
        env:
          ARTIFACTORY_CONTEXTURL: ${{ secrets.ARTIFACTORYCONTEXTURL }}
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORYPASSWORD }}
          ARTIFACTORY_USER: ${{ secrets.ARTIFACTORYUSER }}
          GPG_SIGN_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGN_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      - name: Move Library AAR file to main folder
        run: mv ./\appupdater/build/outputs/aar/appupdater-release.aar ./appupdater-release.aar
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Provided by GH Actions
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
          generate_release_notes: true
          draft: false
          prerelease: false
          files: appupdater-release.aar
      - name: Commit CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: 'docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]'
          file_pattern: CHANGELOG.md
  mavenCentral:
    name: Release to Maven Central
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Make Gradle executable
        run: chmod +x gradlew
      - name: Generate Maven Central artifact and publish release and upload
        run: ./gradlew clean build signAarPublication publish
        env:
          OSSRH_PASSWORD: ${{ secrets.OSSRHPASSWORD }}
          OSSRH_USER: ${{ secrets.OSSRHUSER }}
          GPG_SIGN_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_SIGN_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
      - name: Finish Up
        run: echo Upload successful. Maintainers can proceed onto https://s01.oss.sonatype.org to release the artifacts when capable


